name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  MIX_ENV: test

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: ['1.18', '1.17']
        otp: ['27', '26']
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}
        
    - name: Cache deps
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
        
    - name: Cache _build
      uses: actions/cache@v4
      with:
        path: _build
        key: ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}-
          
    - name: Install dependencies
      run: mix deps.get
      
    - name: Check formatting
      run: mix format --check-formatted
      
    - name: Compile
      run: mix compile --warnings-as-errors
      
    - name: Run tests
      run: mix test
      
  dialyzer:
    name: Dialyzer
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: ['1.18']
        otp: ['27']
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}
        
    - name: Cache deps
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
        
    - name: Cache PLT
      uses: actions/cache@v4
      with:
        path: priv/plts
        key: ${{ runner.os }}-plt-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-plt-${{ matrix.otp }}-${{ matrix.elixir }}-
          
    - name: Install dependencies
      run: mix deps.get
      
    - name: Compile
      run: mix compile
      
    - name: Create PLTs
      run: mix dialyzer --plt
      
    - name: Run Dialyzer
      run: mix dialyzer